function [ cfg ] = seegv_skeletoncfg()
%SEEGV_DEFAULTCFG Summary of this function goes here
% file2load: structure that holds most of the data & parameters
% size_interpolate: brain MRI: choices: wT1, wc1T1, wc2T1
% size_coloredCube: in [mm], "voxel" size of the colored channel values
% colorScale: for example, [-10 10]. If empty, programs adjusts colorscale to 5 & 95 percentile of the data.
% colormap for channel values
% MRI_fileDir: full path to brain MRI NIFTI (.nii) file. Must be normalized to MNI space!
% slicePlanes: planes to plot, options: 'axial','sagittal','coronal'
% model_views: camera view angles at which the snapshot of the 3D model are taken. For some odd reason (camera light?), view(0,90) makes grey background...
% doAnimation_gif: GIF animation of 3D brain model (takes longer time)
    cfg = struct(...         % user interface structure: holds most (but not all!) of the user settings
            'figureNamePrefix', 'myTest_', ...                  % figure name prefix. Program adds automatic suffix to each figure.
            'figurePosition', [1 -479 2880 1472], ...         % position of a figure on screen. For whole screen, evoke a figure, maximize it and type: get(gcf, 'Position')
            'printResolution', 0, ...                                 % choices: 0 (= screen resolution) or 600 (= dpi). Resolution of the figures.                          
            'colorScale', [], ...                               
            'colorMap', jet(128), ...
            'size_interpolate', 1.0, ...                        
            'size_coloredCube', 3.0, ...                        
            'slicePlanes', {{'axial','sagittal','coronal'}},...
            'model_views', [0 0; 0 89.999; 90 0], ... 
            'doAnimation_gif', true ...
        );
end

